name: ci
on: [workflow_dispatch]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup buf
        uses: bufbuild/buf-action@v1
        with:
          version: 1.62.1
          setup_only: true

      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
          cache-dependency-path: './src/be/grpc-server/pom.xml'

      - name: maven build
        working-directory: './src/be/grpc-server'
        run: mvn clean verify -B
